// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:611073378467:web:f2a184fb6288a84083d716',
    messagingSenderId: '611073378467',
    projectId: 'ayuscan-a7138',
    authDomain: 'ayuscan-a7138.firebaseapp.com',
    storageBucket: 'ayuscan-a7138.firebasestorage.app',
    measurementId: 'G-V8YHXP8H4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:611073378467:android:f4c7d1afddbcd16c83d716',
    messagingSenderId: '611073378467',
    projectId: 'ayuscan-a7138',
    storageBucket: 'ayuscan-a7138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:611073378467:ios:2bc577915d2246c083d716',
    messagingSenderId: '611073378467',
    projectId: 'ayuscan-a7138',
    storageBucket: 'ayuscan-a7138.firebasestorage.app',
    iosClientId: '611073378467-9o1g7d4pe1lfm5stggvrmlkhjg0ffmle.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayuscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:611073378467:ios:2bc577915d2246c083d716',
    messagingSenderId: '611073378467',
    projectId: 'ayuscan-a7138',
    storageBucket: 'ayuscan-a7138.firebasestorage.app',
    iosClientId: '611073378467-9o1g7d4pe1lfm5stggvrmlkhjg0ffmle.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayuscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:611073378467:web:33f53d99bcfb75d283d716',
    messagingSenderId: '611073378467',
    projectId: 'ayuscan-a7138',
    authDomain: 'ayuscan-a7138.firebaseapp.com',
    storageBucket: 'ayuscan-a7138.firebasestorage.app',
    measurementId: 'G-GS10X0F3C1',
  );
}
